name: Trigger auto deployment for node-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node-app-AutoDeployTrigger-4edb0729-9390-4bed-9fd7-e175f48387b1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: fabmedical1234.azurecr.io
          username: ${{ secrets.NODEAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NODEAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fabmedical1234.azurecr.io/node-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODEAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n node-app -g aiw-cloudnativedemos2 --server fabmedical1234.azurecr.io --username  ${{ secrets.NODEAPP_REGISTRY_USERNAME }} --password ${{ secrets.NODEAPP_REGISTRY_PASSWORD }}
            az containerapp update -n node-app -g aiw-cloudnativedemos2 --image fabmedical1234.azurecr.io/node-app:${{ github.sha }}
